README.md
RealtimeTTS/engines/coqui_engine.py
RealtimeTTS/text_to_stream.py
setup.py
tests/openaitts_test.py

v0.3.31, fixes for #17/#18

---

RealtimeTTS/engines/coqui_engine.py

This pull request introduces the ability to manually select a torch device using the `device` parameter in CoquiEngine's constructor. Specifically, changes on lines 467-472 ensure that the device choice is correctly handled, with automatic fallback if no device is provided or if the provided device is invalid.
To maintain code cleanliness and conciseness, the `use_mps` class variable has been removed. However, it's important to note that this change may potentially impact existing user code that relies on the `use_mps` variable.
Additionally, I've locally tested this code to ensure its functionality.
I'm open to any discussions regarding these changes.

Add manual device choice

---

example_fast_api/static/tts.js

Currently the audio in the frontend plays after it has streamed the whole audio. This PR fixes the issue to play the audio as soon as the first chunk comes in.
@KoljaB

frontend: direct stream to audio tag

---

RealtimeTTS/engines/base_engine.py
RealtimeTTS/engines/elevenlabs_engine.py
example_fast_api/async_server.py
example_rvc/rvc/infer/modules/ipex/attention.py
example_rvc/rvc/infer/modules/ipex/hijacks.py
example_rvc/rvc/tools/rvc_for_realtime.py
example_rvc/xtts_rvc_llm.py
example_rvc/xtts_rvc_synthesizer.py

removed unnecessary imports

---

README.md

This PR introduces several improvements to the documentation for RealtimeTTS, focusing on enhancing clarity, consistency, and overall readability. The following changes have been made:
- Improved phrasing for better comprehension.
- Ensured consistent terminology and formatting throughout the document.
These modifications aim to provide a clearer understanding for users and developers interacting with RealtimeTTS, ultimately improving the documentation experience.

Enhance Clarity and Consistency in Documentation

---

README.md

Added Badges in Readme

---

README.md

I have added buttons for back to top , GitHub , also added contributors list and fixed typo and grammar part

Doc:- update Readme.md 

---

requirements.txt
tests/multilang_tts_test.py

Added Korean dummy generator and Audio Engines.

Update: Add Korean language in 'Multilang_tts_test.py'

---

tests/multilang_tts_test.py

This PR adds support for Arabic ("ar") language to the text-to-speech (TTS) system across multiple engines including Coqui, Azure, Elevenlabs, and System. The changes allow synthesis of Arabic sentences, in addition to the existing languages, with appropriate voice mappings for each engine.

added arabic language

---

tests/multilang_tts_test.py

hi @KoljaB, I've added Hindi language support in the ```multilang_tts_test.py``` . Since around 60% of the population in india speaks ```Hindi```, this will help make the feature more accessible.

Add hindi language in ```multilang_tts_test.py```

---

tests/multilang_tts_test.py

added portuguese language support.

Add portuguese language in ```multilang_tts_test.py```

---

tests/multilang_tts_test.py

Fixed conflicts for Russian language in ```multilang_tts_test.py```

---

tests/multilang_tts_test.py

added Indonesian language support.

Add Indonesian language in ```multilang_tts_test.py```

---

tests/multilang_tts_test.py

added Vietnamese language support.

Add Vietnamese language in ```multilang_tts_test.py```

---

tests/multilang_tts_test.py

added Bengali language support(spoken by 278M people).

Add Bengali language in ```multilang_tts_test.py```

---

tests/multilang_tts_test.py

Add dutch language in ```multilang_tts_test.py```

---

tests/multilang_tts_test.py

added Ukrainian language support.

Add Ukrainian language in ```multilang_tts_test.py```

---

tests/multilang_tts_test.py

added belarusian language support.

Add belarusian language in ```multilang_tts_test.py```

---

RealtimeTTS/threadsafe_generators.py

- Refactored common logic to minimize code duplication, especially for character logging and callbacks.
- Ensured all function names adhere to Python's naming conventions.
- Updated and clarified docstrings for consistency and better understanding.

threadsafe_generators.py

---

tests/multilang_tts_test.py

Add Urdu language in ```multilang_tts_test.py```

---

tests/multilang_tts_test.py

added Marathi language support.

Add Marathi language in ```multilang_tts_test.py```

---

docs/de/api.md
docs/de/contributing.md
docs/de/faq.md
docs/de/index.md
docs/de/installation.md
docs/de/usage.md
docs/en/index.md
docs/es/index.md
docs/fr/index.md
mkdocs.yml

Hey @KoljaB
Similar to #176 
I've added `German` language in the docs so that the documentation is more accessible.
Here are screen shots for your reference:
Please review it and let me know the changes.

Add German docs

---

tests/multilang_tts_test.py

added Telugu language support.

Add Telugu language in ```multilang_tts_test.py```

---

docs/it/api.md
docs/it/contributing.md
docs/it/faq.md
docs/it/index.md
docs/it/installation.md
docs/it/usage.md
mkdocs.yml

Hey @KoljaB 
I've added `italian` language in the docs so that the documentation is more accessible.
Here are screen shots for your reference:
Please review it and let me know the changes.

Add italian docs

---

tests/multilang_tts_test.py

Add tamil language in ```multilang_tts_test.py```

---

tests/multilang_tts_test.py

added gujarati language support.

Add gujarati language in ```multilang_tts_test.py```

---

tests/multilang_tts_test.py

Add Czech language in ```multilang_tts_test.py```

---

tests/multilang_tts_test.py

added Hungarian language support.

Add Hungarian language in ```multilang_tts_test.py```

---

tests/multilang_tts_test.py

added Malayalam language support.

Add Malayalam language in ```multilang_tts_test.py```

---

tests/multilang_tts_test.py

added kannada language support.

Add kannada language in ```multilang_tts_test.py```

---

tests/multilang_tts_test.py

added nepali language support.

Add nepali language in ```multilang_tts_test.py```

---

tests/multilang_tts_test.py

Thai langaue is used in thailand by more than 69 Million people.

Added Thai language

---

docs/pt/api.md
docs/pt/contributing.md
docs/pt/faq.md
docs/pt/index.md
docs/pt/installation.md
docs/pt/usage.md
mkdocs.yml

Hey @KoljaB, I've added docs for Portuguese language. 
Please review it and let me know the changes.

Add portuguese docs

---

example_fast_api/server.py

Updated server.py in fast_api example to add Kokoro TTS support.

Kokoro support for fast_api example server.py

---

example_fast_api/async_server.py

Updated async_server.py in fast_api example to add support for Kokoro TTS engine.

Kokoro support in async_server.py for fast_api example

---

README.md

change pip install for orpheus (was kokoro)

Update README.md Orpheus typo

---

README.md

Update README.md link to orpheus example
